spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_service
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
    drop-first: true
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
server:
  port: 8083
debug: true