spring:
  application:
    name: recipe-service
  datasource:
    url: jdbc:postgresql://localhost:5432/recipe_service
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
    drop-first: true